### ISSUE TITLE
关于资料的版权问题

### ISSUE THREAD

**Issue by akirakusen** [Servon-Lee/HHU_course#5]
你好！我是项目[lib-cs-hhu](https://github.com/Ricky-Chu/lib-cs-hhu)的开发者
想借鉴一下您这边的一些资料，不用于任何商业用途
会给您注明资料出处，请问可以吗

**Comment by zewenli98** [comment]
> 你好！我是项目[lib-cs-hhu](https://github.com/Ricky-Chu/lib-cs-hhu)的开发者
> 想借鉴一下您这边的一些资料，不用于任何商业用途
> 会给您注明资料出处，请问可以吗

欢迎，注明出处即可。

**Comment by akirakusen** [comment]
感谢。我会在我的项目里把您的项目的链接挂出来，并且tagged您



发送自我的三星盖乐世智能手机。



-------- 原始信息 --------
发件人： Servon <notifications@github.com>
日期: 2020/9/6 22:33 (GMT+08:00)
收件人： Servon-Lee/HHU_course <HHU_course@noreply.github.com>
抄送： Ricky Chu <qs4869@outlook.com>, Author <author@noreply.github.com>
主题： Re: [Servon-Lee/HHU_course] 关于资料的版权问题 (#5)


你好！我是项目lib-cs-hhu<https://github.com/Ricky-Chu/lib-cs-hhu>的开发者
想借鉴一下您这边的一些资料，不用于任何商业用途
会给您注明资料出处，请问可以吗

欢迎，注明出处即可。

―
